input_device: /dev/input/by-path/pci-0000:00:1f.0-platform-INT33D6:00-event # Power button.
modes:
    laptop:
        - pkill onboard
        - i3-msg bar mode hide
        - i3-msg bar hidden_state hide
          #- xinput enable "Wacom HID 4831 Finger touch"
          #- xinput enable "AT Translated Set 2 keyboard"
          #- xinput enable "SynPS/2 Synaptics TouchPad"
          #- xinput enable "TPPS/2 IBM TrackPoint"
    tablet:
        - onboard &
        - i3-msg bar mode dock
          #- xinput disable "Wacom HID 4831 Finger touch"
          #- xinput disable "AT Translated Set 2 keyboard"
          #- xinput disable "SynPS/2 Synaptics TouchPad"
          #- xinput disable "TPPS/2 IBM TrackPoint"
